from sqlalchemy import Column, Integer, String, Float, DateTime, Date, ForeignKey, UniqueConstraint, Numeric, func, Boolean, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
from datetime import datetime

Base = declarative_base()

class Order(Base):
    __tablename__ = 'orders'

    id = Column(Integer, primary_key=True)
    seller_id = Column(String, nullable=False)
    warehouse_id = Column(String, nullable=False)
    store_order_id = Column(String, nullable=False)
    order_release_id = Column(String, unique=True, nullable=False)
    order_line_id = Column(String, nullable=False)
    seller_order_id = Column(String, nullable=False)
    order_id_fk = Column(String)
    core_item_id = Column(String)
    created_on = Column(DateTime)
    style_id = Column(String)
    seller_sku_code = Column(String, nullable=False)
    sku_id = Column(String)
    myntra_sku_code = Column(String)
    size = Column(String)
    vendor_article_number = Column(String)
    brand = Column(String)
    style_name = Column(String)
    article_type = Column(String)
    article_type_id = Column(String)
    order_status = Column(String)
    packet_id = Column(String)
    seller_packe_id = Column(String)
    courier_code = Column(String)
    order_tracking_number = Column(String)
    seller_warehouse_id = Column(String)
    cancellation_reason_id_fk = Column(String)
    cancellation_reason = Column(String)
    packed_on = Column(DateTime)
    fmpu_date = Column(DateTime)
    inscanned_on = Column(DateTime)
    shipped_on = Column(DateTime)
    delivered_on = Column(DateTime)
    cancelled_on = Column(DateTime)
    rto_creation_date = Column(DateTime)
    lost_date = Column(DateTime)
    return_creation_date = Column(DateTime)
    final_amount = Column(Float, nullable=False)
    total_mrp = Column(Float, nullable=False)
    discount = Column(Float, nullable=False)
    coupon_discount = Column(Float, nullable=False)
    shipping_charge = Column(Float, nullable=False)
    gift_charge = Column(Float, nullable=False)
    tax_recovery = Column(Float, nullable=False)
    city = Column(String)
    state = Column(String)
    zipcode = Column(String)
    is_ship_rel = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    returns = relationship("Return", back_populates="order")
    settlements = relationship("Settlement", back_populates="order")

class Return(Base):
    __tablename__ = 'returns'

    id = Column(Integer, primary_key=True)
    order_release_id = Column(String, ForeignKey('orders.order_release_id'), nullable=False)
    order_line_id = Column(String, nullable=False)
    return_type = Column(String)
    return_date = Column(DateTime)
    packing_date = Column(DateTime)
    delivery_date = Column(DateTime)
    ecommerce_portal_name = Column(String)
    sku_code = Column(String)
    invoice_number = Column(String)
    packet_id = Column(String)
    hsn_code = Column(String)
    product_tax_category = Column(String)
    currency = Column(String)
    customer_paid_amount = Column(Float)
    postpaid_amount = Column(Float)
    prepaid_amount = Column(Float)
    mrp = Column(Float)
    total_discount_amount = Column(Float)
    shipping_case_s = Column(String)
    total_tax_rate = Column(Float)
    igst_amount = Column(Float)
    cgst_amount = Column(Float)
    sgst_amount = Column(Float)
    tcs_amount = Column(Float)
    tds_amount = Column(Float)
    commission_percentage = Column(Float)
    minimum_commission = Column(Float)
    platform_fees = Column(Float)
    total_commission = Column(Float)
    total_commission_plus_tcs_tds_deduction = Column(Float)
    total_logistics_deduction = Column(Float)
    shipping_fee = Column(Float)
    fixed_fee = Column(Float)
    pick_and_pack_fee = Column(Float)
    payment_gateway_fee = Column(Float)
    total_tax_on_logistics = Column(Float)
    article_level = Column(String)
    shipment_zone_classification = Column(String)
    customer_paid_amt = Column(Float)
    total_settlement = Column(Float)
    total_actual_settlement = Column(Float)
    amount_pending_settlement = Column(Float)
    prepaid_commission_deduction = Column(Float)
    prepaid_logistics_deduction = Column(Float)
    prepaid_payment = Column(Float)
    postpaid_commission_deduction = Column(Float)
    postpaid_logistics_deduction = Column(Float)
    postpaid_payment = Column(Float)
    settlement_date_prepaid_comm_deduction = Column(DateTime)
    settlement_date_prepaid_logistics_deduction = Column(DateTime)
    settlement_date_prepaid_payment = Column(DateTime)
    settlement_date_postpaid_comm_deduction = Column(DateTime)
    settlement_date_postpaid_logistics_deduction = Column(DateTime)
    settlement_date_postpaid_payment = Column(DateTime)
    bank_utr_no_prepaid_comm_deduction = Column(String)
    bank_utr_no_prepaid_logistics_deduction = Column(String)
    bank_utr_no_prepaid_payment = Column(String)
    bank_utr_no_postpaid_comm_deduction = Column(String)
    bank_utr_no_postpaid_logistics_deduction = Column(String)
    bank_utr_no_postpaid_payment = Column(String)
    postpaid_amount_other = Column(Float)
    prepaid_amount_other = Column(Float)
    shipping_amount = Column(Float)
    gift_amount = Column(Float)
    additional_amount = Column(Float)
    cess_amount = Column(Float)
    taxable_amount = Column(Float)
    igst_rate = Column(Float)
    cgst_rate = Column(Float)
    sgst_rate = Column(Float)
    cess_rate = Column(Float)
    tcs_igst_rate = Column(Float)
    tcs_sgst_rate = Column(Float)
    tcs_cgst_rate = Column(Float)
    tds_rate = Column(Float)
    brand = Column(String)
    gender = Column(String)
    brand_type = Column(String)
    article_type = Column(String)
    supply_type = Column(String)
    try_and_buy_purchase = Column(Boolean)
    customer_name = Column(String)
    customer_delivery_pin_code = Column(String)
    seller_gstn = Column(String)
    seller_name = Column(String)
    myntra_gstn = Column(String)
    shipping_city = Column(String)
    shipping_pin_code = Column(String)
    shipping_state = Column(String)
    shipping_state_code = Column(String)
    prepaid_commission_percentage = Column(Float)
    prepaid_minimum_commission = Column(Float)
    prepaid_platform_fees = Column(Float)
    prepaid_total_commission = Column(Float)
    prepaid_ship_commission_charge = Column(Float)
    prepaid_gift_commission_charge = Column(Float)
    prepaid_cod_commission_charge = Column(Float)
    prepaid_cart_discount = Column(Float)
    prepaid_coupon_discount = Column(Float)
    postpaid_commission_percentage = Column(Float)
    postpaid_minimum_commission = Column(Float)
    postpaid_platform_fees = Column(Float)
    postpaid_total_commission = Column(Float)
    postpaid_ship_commission_charge = Column(Float)
    postpaid_gift_commission_charge = Column(Float)
    postpaid_cod_commission_charge = Column(Float)
    postpaid_cart_discount = Column(Float)
    postpaid_coupon_discount = Column(Float)
    seller_order_id = Column(String)
    tcs_amount_prepaid = Column(Float)
    tcs_amount_postpaid = Column(Float)
    tds_amount_prepaid = Column(Float)
    tds_amount_postpaid = Column(Float)
    seller_tier = Column(String)
    techEnablement_prepaid = Column(Float)
    techEnablement_postpaid = Column(Float)
    airLogistics_prepaid = Column(Float)
    airLogistics_postpaid = Column(Float)
    royaltyCharges_prepaid = Column(Float)
    royaltyCharges_postpaid = Column(Float)
    royaltyPercent_prepaid = Column(Float)
    royaltyPercent_postpaid = Column(Float)
    marketingCharges_prepaid = Column(Float)
    marketingCharges_postpaid = Column(Float)
    marketingPercent_prepaid = Column(Float)
    marketingPercent_postpaid = Column(Float)
    marketingContribution_prepaid = Column(Float)
    marketingContribution_postpaid = Column(Float)
    forwardAdditionalCharges_prepaid = Column(Float)
    forwardAdditionalCharges_postpaid = Column(Float)

    # Relationships
    order = relationship("Order", back_populates="returns")
    settlements = relationship("Settlement", back_populates="return_record")

class Settlement(Base):
    __tablename__ = 'settlements'
    
    id = Column(Integer, primary_key=True)
    order_release_id = Column(String(255), ForeignKey('orders.order_release_id', ondelete='CASCADE'), nullable=False)
    order_line_id = Column(String, nullable=False)
    return_type = Column(String)
    return_date = Column(DateTime)
    packing_date = Column(DateTime)
    delivery_date = Column(DateTime)
    ecommerce_portal_name = Column(String)
    sku_code = Column(String)
    invoice_number = Column(String)
    packet_id = Column(String)
    hsn_code = Column(String)
    product_tax_category = Column(String)
    currency = Column(String)
    customer_paid_amount = Column(Float)
    postpaid_amount = Column(Float)
    prepaid_amount = Column(Float)
    mrp = Column(Float)
    total_discount_amount = Column(Float)
    shipping_case = Column(String)
    total_tax_rate = Column(Float)
    igst_amount = Column(Float)
    cgst_amount = Column(Float)
    sgst_amount = Column(Float)
    tcs_amount = Column(Float)
    tds_amount = Column(Float)
    commission_percentage = Column(Float)
    minimum_commission = Column(Float)
    platform_fees = Column(Float)
    total_commission = Column(Float)
    total_commission_plus_tcs_tds_deduction = Column(Float)
    total_logistics_deduction = Column(Float)
    shipping_fee = Column(Float)
    fixed_fee = Column(Float)
    pick_and_pack_fee = Column(Float)
    payment_gateway_fee = Column(Float)
    total_tax_on_logistics = Column(Float)
    article_level = Column(String)
    shipment_zone_classification = Column(String)
    customer_paid_amt = Column(Float)
    total_expected_settlement = Column(Float)
    total_actual_settlement = Column(Float)
    amount_pending_settlement = Column(Float)
    prepaid_commission_deduction = Column(Float)
    prepaid_logistics_deduction = Column(Float)
    prepaid_payment = Column(Float)
    postpaid_commission_deduction = Column(Float)
    postpaid_logistics_deduction = Column(Float)
    postpaid_payment = Column(Float)
    settlement_date_prepaid_comm_deduction = Column(DateTime)
    settlement_date_prepaid_logistics_deduction = Column(DateTime)
    settlement_date_prepaid_payment = Column(DateTime)
    settlement_date_postpaid_comm_deduction = Column(DateTime)
    settlement_date_postpaid_logistics_deduction = Column(DateTime)
    settlement_date_postpaid_payment = Column(DateTime)
    bank_utr_no_prepaid_comm_deduction = Column(String)
    bank_utr_no_prepaid_logistics_deduction = Column(String)
    bank_utr_no_prepaid_payment = Column(String)
    bank_utr_no_postpaid_comm_deduction = Column(String)
    bank_utr_no_postpaid_logistics_deduction = Column(String)
    bank_utr_no_postpaid_payment = Column(String)
    postpaid_amount_other = Column(Float)
    prepaid_amount_other = Column(Float)
    shipping_amount = Column(Float)
    gift_amount = Column(Float)
    additional_amount = Column(Float)
    cess_amount = Column(Float)
    taxable_amount = Column(Float)
    igst_rate = Column(Float)
    cgst_rate = Column(Float)
    sgst_rate = Column(Float)
    cess_rate = Column(Float)
    tcs_igst_rate = Column(Float)
    tcs_sgst_rate = Column(Float)
    tcs_cgst_rate = Column(Float)
    tds_rate = Column(Float)
    brand = Column(String)
    gender = Column(String)
    brand_type = Column(String)
    article_type = Column(String)
    supply_type = Column(String)
    try_and_buy_purchase = Column(Boolean)
    customer_name = Column(String)
    customer_delivery_pin_code = Column(String)
    seller_gstn = Column(String)
    seller_name = Column(String)
    myntra_gstn = Column(String)
    shipping_city = Column(String)
    shipping_pin_code = Column(String)
    shipping_state = Column(String)
    shipping_state_code = Column(String)
    prepaid_commission_percentage = Column(Float)
    prepaid_minimum_commission = Column(Float)
    prepaid_platform_fees = Column(Float)
    prepaid_total_commission = Column(Float)
    prepaid_ship_commission_charge = Column(Float)
    prepaid_gift_commission_charge = Column(Float)
    prepaid_cod_commission_charge = Column(Float)
    prepaid_cart_discount = Column(Float)
    prepaid_coupon_discount = Column(Float)
    postpaid_commission_percentage = Column(Float)
    postpaid_minimum_commission = Column(Float)
    postpaid_platform_fees = Column(Float)
    postpaid_total_commission = Column(Float)
    postpaid_ship_commission_charge = Column(Float)
    postpaid_gift_commission_charge = Column(Float)
    postpaid_cod_commission_charge = Column(Float)
    postpaid_cart_discount = Column(Float)
    postpaid_coupon_discount = Column(Float)
    seller_order_id = Column(String)
    tcs_amount_prepaid = Column(Float)
    tcs_amount_postpaid = Column(Float)
    tds_amount_prepaid = Column(Float)
    tds_amount_postpaid = Column(Float)
    seller_tier = Column(String)
    techEnablement_prepaid = Column(Float)
    techEnablement_postpaid = Column(Float)
    airLogistics_prepaid = Column(Float)
    airLogistics_postpaid = Column(Float)
    royaltyCharges_prepaid = Column(Float)
    royaltyCharges_postpaid = Column(Float)
    royaltyPercent_prepaid = Column(Float)
    royaltyPercent_postpaid = Column(Float)
    marketingCharges_prepaid = Column(Float)
    marketingCharges_postpaid = Column(Float)
    marketingPercent_prepaid = Column(Float)
    marketingPercent_postpaid = Column(Float)
    marketingContribution_prepaid = Column(Float)
    marketingContribution_postpaid = Column(Float)
    forwardAdditionalCharges_prepaid = Column(Float)
    forwardAdditionalCharges_postpaid = Column(Float)

    # Relationships
    order = relationship("Order", back_populates="settlements")
    return_record = relationship("Return", back_populates="settlements")
    settlement_history = relationship("SettlementHistory", back_populates="settlement")

class SettlementHistory(Base):
    __tablename__ = 'settlement_history'
    
    id = Column(Integer, primary_key=True)
    settlement_id = Column(Integer, ForeignKey('settlements.id'), nullable=False)
    settlement_date = Column(DateTime, nullable=False)
    settlement_status = Column(String, nullable=False)
    amount_settled = Column(Float, nullable=False)
    bank_utr_number = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    settlement = relationship("Settlement", back_populates="settlement_history")

class SettlementDate(Base):
    __tablename__ = 'settlement_dates'

    id = Column(Integer, primary_key=True)
    date = Column(DateTime, unique=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

class MonthlyReconciliation(Base):
    __tablename__ = 'monthly_reconciliation'

    id = Column(Integer, primary_key=True)
    month = Column(String, unique=True, nullable=False)
    total_orders = Column(Integer, nullable=False)
    total_returns = Column(Integer, nullable=False)
    total_settlements = Column(Integer, nullable=False)
    total_amount = Column(Float, nullable=False)
    total_settled = Column(Float, nullable=False)
    total_pending = Column(Float, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow) 